import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import React from "react";
import NoteProvider from "@/app/context/NoteProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NoteProvider>
      <html lang="en">
        <body>
          <Navbar></Navbar>
          {children}
        </body>
      </html>
    </NoteProvider>
  );
}
